# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.convert = QtWidgets.QPushButton(parent=self.centralwidget, clicked=lambda: self.convertted())
        self.convert.setGeometry(QtCore.QRect(30, 100, 75, 23))
        self.convert.setObjectName("Convert")
        self.radioButton1 = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.radioButton1.setGeometry(QtCore.QRect(10, 40, 82, 17))
        self.radioButton1.setObjectName("radioButton1")
        self.radioButton2 = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.radioButton2.setGeometry(QtCore.QRect(80, 40, 82, 17))
        self.radioButton2.setObjectName("radioButton2")
        self.Title = QtWidgets.QLabel(parent=self.centralwidget)
        self.Title.setGeometry(QtCore.QRect(80, 10, 111, 16))
        self.Title.setObjectName("Title")
        self.result = QtWidgets.QLabel(parent=self.centralwidget)
        self.result.setGeometry(QtCore.QRect(20, 130, 250, 90))
        self.result.setText("")
        self.result.setObjectName("result")
        self.clear = QtWidgets.QPushButton(parent=self.centralwidget, clicked=lambda: self.clearred())
        self.clear.setGeometry(QtCore.QRect(150, 100, 75, 23))
        self.clear.setObjectName("Clear")
        self.radioButton3 = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.radioButton3.setGeometry(QtCore.QRect(170, 40, 82, 17))
        self.radioButton3.setObjectName("radioButton3")
        self.part = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.part.setGeometry(QtCore.QRect(90, 70, 151, 20))
        self.part.setObjectName("lineEdit")
        self.Title_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.Title_2.setGeometry(QtCore.QRect(10, 70, 91, 16))
        self.Title_2.setObjectName("Title_2")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Steel Conversion "))
        self.convert.setText(_translate("MainWindow", "Convert"))
        self.radioButton1.setText(_translate("MainWindow", "Primary"))
        self.radioButton2.setText(_translate("MainWindow", "Secondary"))
        self.Title.setText(_translate("MainWindow", "Steel Conversion"))
        self.clear.setText(_translate("MainWindow", "Clear"))
        self.radioButton3.setText(_translate("MainWindow", "Eave "))
        self.Title_2.setText(_translate("MainWindow", "Part Number"))


